import gzip
import os
import requests
from datetime import datetime

from google.cloud import bigquery, storage
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.models.param import Param

KEY_PATH = "/opt/airflow/keys/gcp-key.json"

@dag(
    dag_id="08_gcp_taxi",
    description="Extracts NYC taxi data, streams into staging, and merges into BigQuery",
    schedule_interval=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    params={
        "taxi": Param("yellow", enum=["yellow", "green"], description="Select taxi type"),
        "year": Param("2019", enum=["2019", "2020"], description="Select year"),
        "month": Param("01", enum=[f"{i:02d}" for i in range(1, 13)], description="Select month"),
    },
    tags=["zoomcamp"],
)
def gcp_taxi_pipeline():

    @task
    def set_label(**context) -> dict:
        """Constructs variables equivalent to Kestra vars."""
        params = context["params"]
        taxi = params["taxi"]
        year = params["year"]
        month = params["month"]
        file_name = f"{taxi}_tripdata_{year}-{month}.csv"

        gcp_bucket = Variable.get("GCP_BUCKET_NAME")
        gcp_dataset = Variable.get("GCP_DATASET")
        
        return {
            "taxi": taxi,
            "file_name": file_name,
            "gcs_table": f"gs://{gcp_bucket}/{file_name}",
            "gcp_bucket": gcp_bucket,
            "table": f"{gcp_dataset}.{taxi}_tripdata_{year}-{month}",
            "url": f"https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{taxi}/{file_name}.gz"
        }

    @task
    def extract(meta: dict) -> str:
        """Downloads gzipped CSV and extracts it locally."""
        url = meta["url"]
        local_filepath = f"/tmp/{meta['file_name']}"
        
        response = requests.get(url, stream=True)
        response.raise_for_status()

        with gzip.GzipFile(fileobj=response.raw) as gz, open(local_filepath, "wb") as out_file:
            out_file.write(gz.read())
        return local_filepath

    @task
    def upload_to_gcs(meta: dict):
        client = storage.Client.from_service_account_json(KEY_PATH)
        bucket = client.bucket(meta["gcp_bucket"])
        blob = bucket.blob(meta['file_name'])
        blob.upload_from_filename(f"/tmp/{meta['file_name']}")

    @task.branch
    def branch_by_taxi_type(meta: dict) -> str:
        """Routes execution path based on selected taxi type (If task in Kestra)."""
        if meta["taxi"] == "yellow":
            return "yellow_workflow.create_tables"
        return "green_workflow.create_tables"

    # --- YELLOW TAXI PIPELINE ---
    @task(task_id="yellow_workflow.create_tables")
    def bq_yellow_tripdata(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        gcp_dataset = Variable.get("GCP_DATASET")

        sql_query=f"""
            CREATE TABLE IF NOT EXISTS `{gcp_project_id}.{gcp_dataset}.yellow_tripdata`
            (
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                tpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                tpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                passenger_count INTEGER OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. TRUE = store and forward trip, FALSE = not a store and forward trip'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            PARTITION BY DATE(tpep_pickup_datetime);
        """

        client.query(sql_query).result()

    @task(task_id="yellow_workflow.bq_yellow_table_ext")
    def bq_yellow_table_ext(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        table = meta['table']
        gcs_table = meta["gcs_table"]
        sql_query=f"""
            CREATE OR REPLACE EXTERNAL TABLE `{gcp_project_id}.{table}_ext`
            (
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                tpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                tpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                passenger_count INTEGER OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. TRUE = store and forward trip, FALSE = not a store and forward trip'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            OPTIONS (
                format='CSV',
                uris=['{gcs_table}'],
                skip_leading_rows=1,
                ignore_unknown_values=TRUE
            );
        """
        client.query(sql_query).result()
        
    @task(task_id="yellow_workflow.copy_and_merge")
    def bq_yellow_table_tmp_and_merge(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        gcp_dataset = Variable.get("GCP_DATASET")
        table = meta['table']
        file_name = meta['file_name']
        sql_query=f"""
            CREATE OR REPLACE TABLE `{gcp_project_id}.{table}`AS
            SELECT
                MD5(CONCAT(
                    COALESCE(CAST(VendorID AS STRING), ""),
                    COALESCE(CAST(tpep_pickup_datetime AS STRING), ""),
                    COALESCE(CAST(tpep_dropoff_datetime AS STRING), ""),
                    COALESCE(CAST(PULocationID AS STRING), ""),
                    COALESCE(CAST(DOLocationID AS STRING), "")
                )) AS unique_row_id,
                "{file_name}" AS filename,
                *
            FROM `{gcp_project_id}.{table}_ext`;

            MERGE INTO `{gcp_project_id}.{gcp_dataset}.yellow_tripdata` T
            USING `{gcp_project_id}.{table}` S ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
                INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime,
                        passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID,
                        DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount,
                        improvement_surcharge, total_amount, congestion_surcharge)
                VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime,
                        S.passenger_count, S.trip_distance, S.RatecodeID, S.store_and_fwd_flag, S.PULocationID,
                        S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount,
                        S.improvement_surcharge, S.total_amount, S.congestion_surcharge);
        """
        client.query(sql_query).result()


    # --- GREEN TAXI PIPELINE ---
    @task(task_id="green_workflow.create_tables")
    def bq_green_tripdata(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        gcp_dataset = Variable.get("GCP_DATASET")
        sql_query = f"""
            CREATE TABLE IF NOT EXISTS `{gcp_project_id}.{gcp_dataset}.green_tripdata`
            (
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                lpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                lpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. Y= store and forward trip N= not a store and forward trip'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                passenger_count INT64 OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                trip_type STRING OPTIONS (description = 'A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be altered by the driver. 1= Street-hail 2= Dispatch'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            PARTITION BY DATE(lpep_pickup_datetime);
        """
        client.query(sql_query).result()

    @task(task_id="green_workflow.green_table_ext")
    def bq_green_table_ext(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        table = meta['table']
        gcs_table = meta["gcs_table"]
        sql_query = f"""
            CREATE OR REPLACE EXTERNAL TABLE `{gcp_project_id}.{table}_ext`
            (
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                lpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                lpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. Y= store and forward trip N= not a store and forward trip'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                passenger_count INT64 OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                trip_type STRING OPTIONS (description = 'A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be altered by the driver. 1= Street-hail 2= Dispatch'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            OPTIONS (
                format='CSV',
                uris=['{gcs_table}'],
                skip_leading_rows=1,
                ignore_unknown_values=TRUE
            );
        """
        client.query(sql_query).result()

    @task(task_id="green_workflow.copy_and_merge")
    def bq_green_table_tmp_and_merge(meta: dict):
        client = bigquery.Client.from_service_account_json(KEY_PATH)
        gcp_project_id = Variable.get("GCP_PROJECT_ID")
        gcp_dataset = Variable.get("GCP_DATASET")
        table = meta['table']
        file_name = meta['file_name']
        sql_query = f"""
            CREATE OR REPLACE TABLE `{gcp_project_id}.{table}`AS
            SELECT
                MD5(CONCAT(
                    COALESCE(CAST(VendorID AS STRING), ""),
                    COALESCE(CAST(lpep_pickup_datetime AS STRING), ""),
                    COALESCE(CAST(lpep_dropoff_datetime AS STRING), ""),
                    COALESCE(CAST(PULocationID AS STRING), ""),
                    COALESCE(CAST(DOLocationID AS STRING), "")
                )) AS unique_row_id,
                "{file_name}" AS filename,
                *
            FROM `{gcp_project_id}.{table}_ext`;

            MERGE INTO `{gcp_project_id}.{gcp_dataset}.green_tripdata` T
            USING `{gcp_project_id}.{table}` S ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
                INSERT (unique_row_id, filename, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime,
                    store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count,
                    trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee,
                    improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)
                VALUES (S.unique_row_id, S.filename, S.VendorID, S.lpep_pickup_datetime, S.lpep_dropoff_datetime,
                    S.store_and_fwd_flag, S.RatecodeID, S.PULocationID, S.DOLocationID, S.passenger_count,
                    S.trip_distance, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.ehail_fee,
                    S.improvement_surcharge, S.total_amount, S.payment_type, S.trip_type, S.congestion_surcharge);
        """
        client.query(sql_query).result()

    @task(trigger_rule="none_failed_min_one_success")
    def purge_files(file_path: dict):
        """Removes extracted temporary CSV file (Equivalent to PurgeCurrentExecutionFiles)."""
        if os.path.exists(file_path):
                    os.remove(file_path)

    # Pipeline Wiring
    metadata = set_label()
    downloaded_file = extract(metadata)
    upload = upload_to_gcs(metadata)
    branch = branch_by_taxi_type(metadata)

    # Yellow branch workflow
    y_create = bq_yellow_tripdata(metadata)
    y_ext = bq_yellow_table_ext(metadata)
    y_merge = bq_yellow_table_tmp_and_merge(metadata)
    
    # Green branch workflow
    g_create = bq_green_tripdata(metadata)
    g_ext = bq_green_table_ext(metadata)
    g_merge = bq_green_table_tmp_and_merge(metadata)

    purge = purge_files(downloaded_file)

    # Dependencies
    metadata >> downloaded_file >> upload >> branch
    branch >> [y_create, g_create]
    y_create >> y_ext >> y_merge >> purge
    g_create >> g_ext >> g_merge >> purge

gcp_taxi_pipeline()