
import gzip
import os
import requests
from datetime import datetime
from pandas import date_range

from google.cloud import bigquery, storage
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.models.param import Param

KEY_PATH = "/opt/airflow/keys/gcp-key.json"
TAXI_CONFIGS = {
    "green": {
        "schedule": "0 9 1 * *",
        "schema_sql": f"""
            CREATE TABLE IF NOT EXISTS `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata`(
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record.'),
                lpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                lpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                store_and_fwd_flag STRING,
                RatecodeID STRING,
                PULocationID STRING,
                DOLocationID STRING,
                passenger_count INT64,
                trip_distance NUMERIC,
                fare_amount NUMERIC,
                extra NUMERIC,
                mta_tax NUMERIC,
                tip_amount NUMERIC,
                tolls_amount NUMERIC,
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC,
                total_amount NUMERIC,
                payment_type INTEGER,
                trip_type STRING,
                congestion_surcharge NUMERIC
            )
            PARTITION BY DATE(lpep_pickup_datetime);

            CREATE OR REPLACE EXTERNAL TABLE `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata_ext`(
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                lpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                lpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. Y= store and forward trip N= not a store and forward trip'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                passenger_count INT64 OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                ehail_fee NUMERIC,
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                trip_type STRING OPTIONS (description = 'A code indicating whether the trip was a street-hail or a dispatch that is automatically assigned based on the metered rate in use but can be altered by the driver. 1= Street-hail 2= Dispatch'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            OPTIONS (
                format = 'CSV',
                uris = ['{{gcs_table}}'],
                skip_leading_rows = 1,
                ignore_unknown_values = TRUE
            );
        """,
        "transform_n_merge_sql": f"""
            CREATE OR REPLACE TABLE `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata_stg` AS
            SELECT 
                MD5(CONCAT(
                    COALESCE(CAST(VendorID AS STRING), ""),
                    COALESCE(CAST(lpep_pickup_datetime AS STRING), ""),
                    COALESCE(CAST(lpep_dropoff_datetime AS STRING), ""),
                    COALESCE(CAST(PULocationID AS STRING), ""),
                    COALESCE(CAST(DOLocationID AS STRING), "")
                )) AS unique_row_id,
                "{{file_name}}" AS filename,
                SAFE_CAST(VendorID AS STRING) AS VendorID,
                lpep_pickup_datetime,
                lpep_dropoff_datetime,
                SAFE_CAST(store_and_fwd_flag AS STRING) AS store_and_fwd_flag,
                SAFE_CAST(RatecodeID AS STRING) AS RatecodeID,
                SAFE_CAST(PULocationID AS STRING) AS PULocationID,
                SAFE_CAST(DOLocationID AS STRING) AS DOLocationID,
                SAFE_CAST(passenger_count AS INT64) AS passenger_count,
                SAFE_CAST(trip_distance AS NUMERIC) AS trip_distance,
                SAFE_CAST(fare_amount AS NUMERIC) AS fare_amount,
                SAFE_CAST(extra AS NUMERIC) AS extra,
                SAFE_CAST(mta_tax AS NUMERIC) AS mta_tax,
                SAFE_CAST(tip_amount AS NUMERIC) AS tip_amount,
                SAFE_CAST(tolls_amount AS NUMERIC) AS tolls_amount,
                SAFE_CAST(ehail_fee AS NUMERIC) AS ehail_fee,
                SAFE_CAST(improvement_surcharge AS NUMERIC) AS improvement_surcharge,
                SAFE_CAST(total_amount AS NUMERIC) AS total_amount,
                SAFE_CAST(payment_type AS INT64) AS payment_type,
                SAFE_CAST(trip_type AS STRING) AS trip_type,
                SAFE_CAST(congestion_surcharge AS NUMERIC) AS congestion_surcharge
            FROM `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata_ext`;

            MERGE INTO `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata` T
            USING `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata_stg` S ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
                INSERT (unique_row_id, filename, VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)
                VALUES (S.unique_row_id, S.filename, S.VendorID, S.lpep_pickup_datetime, S.lpep_dropoff_datetime, S.store_and_fwd_flag, S.RatecodeID, S.PULocationID, S.DOLocationID, S.passenger_count, S.trip_distance, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.ehail_fee, S.improvement_surcharge, S.total_amount, S.payment_type, S.trip_type, S.congestion_surcharge);
                
            DROP TABLE IF EXISTS `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.green_tripdata_stg`;
        """
    },
    "yellow": {
        "schedule": "0 10 1 * *",
        "schema_sql": f"""
            CREATE TABLE IF NOT EXISTS `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata`(
                unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),      
                VendorID STRING,
                tpep_pickup_datetime TIMESTAMP,
                tpep_dropoff_datetime TIMESTAMP,
                passenger_count INTEGER,
                trip_distance NUMERIC,
                RatecodeID STRING,
                store_and_fwd_flag STRING,
                PULocationID STRING,
                DOLocationID STRING,
                payment_type INTEGER,
                fare_amount NUMERIC,
                extra NUMERIC,
                mta_tax NUMERIC,
                tip_amount NUMERIC,
                tolls_amount NUMERIC,
                improvement_surcharge NUMERIC,
                total_amount NUMERIC,
                congestion_surcharge NUMERIC
            )
            PARTITION BY DATE(tpep_pickup_datetime);

            CREATE OR REPLACE EXTERNAL TABLE `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata_ext`(
                VendorID STRING OPTIONS (description = 'A code indicating the LPEP provider that provided the record. 1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.'),
                tpep_pickup_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was engaged'),
                tpep_dropoff_datetime TIMESTAMP OPTIONS (description = 'The date and time when the meter was disengaged'),
                passenger_count INTEGER OPTIONS (description = 'The number of passengers in the vehicle. This is a driver-entered value.'),
                trip_distance NUMERIC OPTIONS (description = 'The elapsed trip distance in miles reported by the taximeter.'),
                RatecodeID STRING OPTIONS (description = 'The final rate code in effect at the end of the trip. 1= Standard rate 2=JFK 3=Newark 4=Nassau or Westchester 5=Negotiated fare 6=Group ride'),
                store_and_fwd_flag STRING OPTIONS (description = 'This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka "store and forward," because the vehicle did not have a connection to the server. TRUE = store and forward trip, FALSE = not a store and forward trip'),
                PULocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was engaged'),
                DOLocationID STRING OPTIONS (description = 'TLC Taxi Zone in which the taximeter was disengaged'),
                payment_type INTEGER OPTIONS (description = 'A numeric code signifying how the passenger paid for the trip. 1= Credit card 2= Cash 3= No charge 4= Dispute 5= Unknown 6= Voided trip'),
                fare_amount NUMERIC OPTIONS (description = 'The time-and-distance fare calculated by the meter'),
                extra NUMERIC OPTIONS (description = 'Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges'),
                mta_tax NUMERIC OPTIONS (description = '$0.50 MTA tax that is automatically triggered based on the metered rate in use'),
                tip_amount NUMERIC OPTIONS (description = 'Tip amount. This field is automatically populated for credit card tips. Cash tips are not included.'),
                tolls_amount NUMERIC OPTIONS (description = 'Total amount of all tolls paid in trip.'),
                improvement_surcharge NUMERIC OPTIONS (description = '$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015.'),
                total_amount NUMERIC OPTIONS (description = 'The total amount charged to passengers. Does not include cash tips.'),
                congestion_surcharge NUMERIC OPTIONS (description = 'Congestion surcharge applied to trips in congested zones')
            )
            OPTIONS (
                format = 'CSV',
                uris = ['{{gcs_table}}'],
                skip_leading_rows = 1,
                ignore_unknown_values = TRUE
            );
        """,
        "transform_n_merge_sql": f"""
            CREATE OR REPLACE TABLE `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata_stg` AS
            SELECT
                MD5(CONCAT(
                    COALESCE(CAST(VendorID AS STRING), ""),
                    COALESCE(CAST(tpep_pickup_datetime AS STRING), ""),
                    COALESCE(CAST(tpep_dropoff_datetime AS STRING), ""),
                    COALESCE(CAST(PULocationID AS STRING), ""),
                    COALESCE(CAST(DOLocationID AS STRING), "")
                )) AS unique_row_id,
                '{{file_name}}' AS filename,
                SAFE_CAST(VendorID AS STRING) AS VendorID,
                tpep_pickup_datetime,
                tpep_dropoff_datetime,
                SAFE_CAST(passenger_count AS INT64) AS passenger_count,
                SAFE_CAST(trip_distance AS NUMERIC) AS trip_distance,
                SAFE_CAST(RatecodeID AS STRING) AS RatecodeID,
                SAFE_CAST(store_and_fwd_flag AS STRING) AS store_and_fwd_flag,
                SAFE_CAST(PULocationID AS STRING) AS PULocationID,
                SAFE_CAST(DOLocationID AS STRING) AS DOLocationID,
                SAFE_CAST(payment_type AS INT64) AS payment_type,
                SAFE_CAST(fare_amount AS NUMERIC) AS fare_amount,
                SAFE_CAST(extra AS NUMERIC) AS extra,
                SAFE_CAST(mta_tax AS NUMERIC) AS mta_tax,
                SAFE_CAST(tip_amount AS NUMERIC) AS tip_amount,
                SAFE_CAST(tolls_amount AS NUMERIC) AS tolls_amount,
                SAFE_CAST(improvement_surcharge AS NUMERIC) AS improvement_surcharge,
                SAFE_CAST(total_amount AS NUMERIC) AS total_amount,
                SAFE_CAST(congestion_surcharge AS NUMERIC) AS congestion_surcharge
            FROM `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata_ext`;

            MERGE INTO `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata` T
            USING `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata_stg` S ON T.unique_row_id = S.unique_row_id
            WHEN NOT MATCHED THEN
                INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge)
                VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance, S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax, S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge);
                
            DROP TABLE IF EXISTS `{{GCP_PROJECT_ID}}.{{GCP_DATASET}}.yellow_tripdata_stg`;
        """
    }
}

def create_gcp_taxi_dag(taxi_type: str, config: dict):
    dag_id = f"09_gcp_{taxi_type}_scheduled"

    @dag(
        dag_id = dag_id,
        description = "Scheduled/Backfill workflow for NYC {taxi_type.capitalize() data extraction and loading into GCP}",
        schedule = config["schedule"],
        start_date = datetime(2019, 1, 1),
        catchup = True,
        max_active_runs = 1,
        params = {
            "start_year_month": Param(
                default="",
                type=["null","string"],
                description="Optional start month for backfill runs. Leave empty for scheduled/logical date"
            ),
            "end_year_month": Param(
                default="",
                type=["null","string"],
                description="Optional end month for backfill runs. Leave empty for scheduled/logical date"
            ),
        },
        tags = ['zoomcamp', taxi_type]
    )

    def gcp_taxi_scheduled_pipeline():

        @task
        def set_label(**context) -> list[dict]:
            # Airflow context logical_date handles scheduled runs and backfills
            start_ym = context["params"].get("start_year_month")
            end_ym = context["params"].get("end_year_month")

            # Manual trigger with range input
            if start_ym and start_ym.strip():
                start_str = start_ym.strip()
                end_str = end_ym.strip() if end_ym and end_ym.strip() else start_str

                dates = date_range(start=f"{start_str}-01", end=f"{end_str}-01", freq="MS")
                ym_list = [d.strftime("%Y-%m") for d in dates]
            # Automated scheduled run fallback
            else:
                logical_date = context["logical_date"]
                year_month = logical_date.strftime("%Y-%m")

            #Build metadata targets for each month in range
            gcp_bucket_name = Variable.get("GCP_BUCKET_NAME")
            file_targets = []
            for ym in ym_list:
                file_name = f"{taxi_type}_tripdata_{ym}.csv"
                file_targets.append({
                    "year_month": ym,
                    "file_name": file_name,
                    "gcs_table": f"gs://{gcp_bucket_name}/{file_name}",
                    "gcp_bucket_name": gcp_bucket_name,
                    "table": f"zoomcamp.{taxi_type}_tripdata",
                    "url": f"https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{taxi_type}/{file_name}.gz"
                })
            
            return file_targets

        @task
        def process_range(targets: list[dict]):
            gcp_project_id = Variable.get("GCP_PROJECT_ID")
            gcp_bucket_name = Variable.get("GCP_BUCKET_NAME")
            gcp_dataset = Variable.get("GCP_DATASET")
            gcp_location = Variable.get("GCP_LOCATION")

            for meta in targets:
                filename = meta["file_name"]
                url = meta["url"]
                gcs_table = meta["gcs_table"]
                table= meta["table"]
                local_filepath = os.path.join("/tmp", filename)

                # 1. Extract
                response = requests.get(url, stream=True)
                response.raise_for_status()
        
                with gzip.GzipFile(fileobj=response.raw) as gz, open(local_filepath, "wb") as out_file:
                    out_file.write(gz.read())

                # 2. Upload to GCS
                client = storage.Client.from_service_account_json(KEY_PATH)
                bucket = client.bucket(meta["gcp_bucket_name"])
                blob = bucket.blob(meta['file_name'])
                blob.upload_from_filename(f"/tmp/{meta['file_name']}")
    

                # 3. Tripdata and Ext table
                client2 = bigquery.Client.from_service_account_json(KEY_PATH)

                schema_sql = config["schema_sql"].format(
                    GCP_BUCKET_NAME = gcp_bucket_name,
                    GCP_PROJECT_ID = gcp_project_id,
                    GCP_DATASET = gcp_dataset,
                    GCP_LOCATION = gcp_location,
                    table=table,
                    gcs_table=gcs_table,
                    file_name=filename)
                client2.query(schema_sql).result()

                # 4. TMP and merge into target table
                merge_sql = config["transform_n_merge_sql"].format(
                    GCP_BUCKET_NAME = gcp_bucket_name,
                    GCP_PROJECT_ID = gcp_project_id,
                    GCP_DATASET = gcp_dataset,
                    GCP_LOCATION = gcp_location,
                    table=table,
                    gcs_table=gcs_table,
                    file_name=filename)
                client2.query(merge_sql).result()

                # 5. Cleanup local temp files

                if os.path.exists(local_filepath):
                    os.remove(local_filepath)

        # Dependencies wiring
        metadata = set_label()
        process = process_range(metadata)

    return gcp_taxi_scheduled_pipeline()

for taxi, cfg in TAXI_CONFIGS.items():
    globals()[f"09_gcp_{taxi}_scheduled"] = create_gcp_taxi_dag(taxi, cfg)

