FROM apache/airflow:2.9.0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER root

# Install dependencies and Google Cloud SDK (gcloud + bq)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gnupg \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
    && apt-get update && apt-get install -y --no-install-recommends \
    google-cloud-cli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow